src/Entity/Changelog.php
<?php

namespace ODL\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="ODL\Repository\ChangelogRepository")
 */
class Changelog
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime", columnDefinition="timestamp DEFAULT current_timestamp() NOT NULL")
     */
    private $date;

    /**
     * @ORM\Column(type="text")
     */
    private $author;

    /**
     * @ORM\Column(type="text")
     */
    private $cl_type;

    /**
     * @ORM\Column(type="text")
     */
    private $name_universe;

    /**
     * @ORM\Column(type="text")
     */
    private $name_era;

    /**
     * @ORM\Column(type="text")
     */
    private $name_period;

    /**
     * @ORM\Column(type="text")
     */
    private $old_position;

    /**
     * @ORM\Column(type="text")
     */
    private $new_position;

    /**
     * @ORM\Column(type="text")
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $new_title;

    /**
     * @ORM\Column(type="text")
     */
    private $cover;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="text")
     */
    private $link_a;

    /**
     * @ORM\Column(type="text")
     */
    private $link_b;

    /**
     * @ORM\Column(type="text")
     */
    private $is_event;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getClType(): ?string
    {
        return $this->cl_type;
    }

    public function setClType(string $cl_type): self
    {
        $this->cl_type = $cl_type;

        return $this;
    }

    public function getNameUniverse(): ?string
    {
        return $this->name_universe;
    }

    public function setNameUniverse(string $name_universe): self
    {
        $this->name_universe = $name_universe;

        return $this;
    }

    public function getNameEra(): ?string
    {
        return $this->name_era;
    }

    public function setNameEra(string $name_era): self
    {
        $this->name_era = $name_era;

        return $this;
    }

    public function getNamePeriod(): ?string
    {
        return $this->name_period;
    }

    public function setNamePeriod(string $name_period): self
    {
        $this->name_period = $name_period;

        return $this;
    }

    public function getOldPosition(): ?string
    {
        return $this->old_position;
    }

    public function setOldPosition(string $old_position): self
    {
        $this->old_position = $old_position;

        return $this;
    }

    public function getNewPosition(): ?string
    {
        return $this->new_position;
    }

    public function setNewPosition(string $new_position): self
    {
        $this->new_position = $new_position;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getNewTitle(): ?string
    {
        return $this->new_title;
    }

    public function setNewTitle(string $new_title): self
    {
        $this->new_title = $new_title;

        return $this;
    }

    public function getCover(): ?string
    {
        return $this->cover;
    }

    public function setCover(string $cover): self
    {
        $this->cover = $cover;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getLinkA(): ?string
    {
        return $this->link_a;
    }

    public function setLinkA(string $link_a): self
    {
        $this->link_a = $link_a;

        return $this;
    }

    public function getLinkB(): ?string
    {
        return $this->link_b;
    }

    public function setLinkB(string $link_b): self
    {
        $this->link_b = $link_b;

        return $this;
    }

    public function getIsEvent(): ?string
    {
        return $this->is_event;
    }

    public function setIsEvent(string $is_event): self
    {
        $this->is_event = $is_event;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }
}

templates/partial/arc_line.html.twig
<table class='{{ (p is defined) ? 'page_' ~ p : '' }}'>
  <tbody>
    <tr class='ui segment blue line {% if arc.isEvent %}isEvent{% endif %}' id='{{ arc.id }}'>
        <td class='cel_id ui blue left corner label'>
            <span class='icon'>{{ arc.position }}</span>
        </td>
        <td class='cel_img'><img src='{{ coverSource }}'></td>
        <td class='cel_title'>
            <h3>{{ arc.title|unescape }}</h3>
        </td>
        <td class='cel_content'>
            <p>{{ arc.content|unescape|nl2br }}</p>
        </td>
        {% if (era.getLogoLinkA() is not empty) or (era.getLogoLinkB() is not empty) %}
        <td class='cel_publi'>
            <h4>Disponible chez</h4>
            <div class='img_publi'>
                <!-- begin display links -->
                {% if (era.getLogoLinkA() is not empty) %}
                {% if arc.getLinkA() is not empty %}
                <a class='urlUrban' href='{{ arc.getLinkA() }}' target='_blank'>
                    <img src='{{ asset('assets/img/logos/') }}{{ era.getLogoLinkA() }}'>
                </a>
                {% else %}
                <img src='{{ asset('assets/img/logos/') }}{{ era.getLogoLinkA() }}' class='logo_opacity'>
                {% endif %}
                {% endif %}
                {% if (era.getLogoLinkB() is not empty) %}
                {% if arc.getLinkB() is not empty %}
                <a class='urlDctrad' href='{{ arc.getLinkA() }}' target='_blank'>
                    <img src='{{ asset('assets/img/logos/') }}{{ era.getLogoLinkB() }}'>
                </a>
                {% else %}
                <img src='{{ asset('assets/img/logos/') }}{{ era.getLogoLinkB() }}' class='logo_opacity'>
                {% endif %}
                {% endif %}
                <!-- end display links -->
            </div>
        </td>
        {% endif %}
        {% if is_granted('ROLE_EDITOR') %}
        <td>
            <button class="ui basic icon button update_tr">
                <i id='line_{{ arc.id }}' class='fas fa-pen-fancy'></i>
            </button>
            <button class="ui basic icon button btn_trash">
                <i class='fas fa-trash-alt'></i>
            </button>
        </td>
        {% endif %}
    </tr>
  </tbody>
</table>

templates/partial/button_back_to_top.html.twig
<div class='ui basic button' id='btnup'>
    <i class='fas fa-arrow-circle-up'></i>
</div>

templates/partial/card.html.twig
<div class="ui cards">
    {% for card in cards %}
    <div class="card">
        <div class="content">
            <div class="header"><i class="{{ card.icon }} icon"></i>{{ card.title }}</div>
            <div class="description">
                {{ card.description }}
            </div>
        </div>
        <a href="{{ path(card.path) }}">
            <div class="ui bottom attached button">
                <i class="play icon"></i>
            </div>
        </a>
    </div>
    {% endfor %}
</div>

templates/partial/footer.html.twig
<footer>
    <span>
        <p><strong>{% if copyright_website %}&#9400;{{ copyright_website }}{% endif %}</strong></p>
        <p><strong>{% if webmaster %}Developer &#9400;{{ webmaster }}{% endif %}</strong></p>
        <p><strong>{% if copyright_reading_order %}{{ 'Reading order by ' ~ copyright_reading_order }}{% endif %}</strong>
        </p>
    </span>
</footer>

templates/partial/header.html.twig
{% if app_settings.website_banner is defined %}
<header>
    <a href="{{ path('odl_home_page') }}" id="header"></a>
</header>
{% endif %}

templates/partial/javascripts.html.twig
<script type="text/javascript" src="{{ asset('assets/js/jquery.min.js') }}"></script>
<script src="{{ asset('bundles/fosjsrouting/js/router.min.js') }}"></script>
<script src="{{ path('fos_js_routing_js', { callback: 'fos.Router.setData' }) }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/script.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/dist/semantic.min.js') }}"></script>
<script src="{{ asset('node_modules/sweetalert/dist/sweetalert.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/search-bar.js') }}"></script>

templates/partial/menu.html.twig
<div class="ui icon menu" id='up'>
    <a href='{{ path('odl_home_page') }}' title='Home' class='item'>
        <i class='fas fa-home'></i>
    </a>
    {% if is_granted('ROLE_EDITOR') %}
    <a href='{{ path('odl_admin_home') }}' title='PCA' class='item'>
        <i class='fas fa-bars'></i>
    </a>
    <a href='{{ path('odl_admin_add_arc') }}' title='Ajouter un arc' class='item'>
        <i class='fas fa-plus-circle'></i>
    </a>
    {% endif %}
    <div class='right menu'>
      <div class='item'>
      {% include "partial/search-bar.html.twig" %}
      </div>
      {% if app.user.username is defined %}
        <p class='ui basic message item'>{{ "Hello " ~ app.user.username }}</p>
      <a href='{{ path('odl_admin_profile') }}' title='Profil' class='item'>
          {% if app.user.avatar %}
          <img id='user-avatar' src='{{ asset(path_images ~ '/avatars/' ~ app.user.avatar) }}'>
          {% else %}
          <i class='icon user'></i>
          {% endif %}
      </a>
      <a href='{{ path('odl_security_logout') }}' title='Déconnexion' class='item'>
          <i class='fas fa-sign-out-alt'></i>
      </a>
      {% else %}
      <a href='{{ path('odl_security_login') }}' title='Connexion' class='item'>
        <i class='fas fa-sign-in-alt'></i>
      </a>
      {% endif %}
    </div>
</div>

templates/partial/message.html.twig
<!--
message should be an array of the following variables:
  - type: info/error/warning. It could be a color name, size or both. See https://semantic-ui.com/collections/message.html#info for more.
  - title (optionnal)
  - content: it could have some html tags.
-->
<div class="ui {{ message.type }} message">
    {% if message.title is defined and message.title is not empty %}
    <div class="header">{{message.title}}</div>
    {% endif %}
    <p>{{ message.content|raw }}</p>
</div>

templates/partial/message_flash.html.twig
{% if app.flashes is defined %}
{% for label, messages in app.flashes %}
<div class="ui {{ label }} message">
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
</div>
{% endfor %}
{% endif %}

templates/partial/pagination_buttons.html.twig
{% if arcsLength > 20 %}
<div class='btn_pagination {{class_button}}'>
    <button class='btn_prev' name='pagination' style='display: none'><i class='fas fa-chevron-circle-left'></i></button>
    {% set p = (arcsLength / 20)|round(0, 'ceil') %}
    {% for i in 1..p %}
    <button class='btn_page btn_page_{{ i }}' name='pagination'>{{ i }}</button>
    {% endfor %}
    <button class='btn_next' name='pagination'><i class='fas fa-chevron-circle-right'></i></button>
</div>
{% endif %}

templates/partial/search-bar.html.twig
<div class="ui category search">
  <div class="ui transparent icon input">
    <input class="prompt" id="search-bar" type="text" placeholder="Search...">
    <i class="search icon"></i>
  </div>
  <div class="results" id='search-results'></div>
</div>

templates/partial/stylesheets.html.twig
<link rel="stylesheet" href="/assets/css/general.css">
<link rel="stylesheet" href="/assets/css/style.css">
<link rel="stylesheet" href="/assets/css/new-style.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
    integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="/assets/dist/semantic.min.css">